#!/bin/sh

# Copyright (C) 2017, Yasumasa Suenaga
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.


BASEDIR=`dirname $0`

if [ -z "$JAVA_HOME" ]; then
  echo '$JAVA_HOME is required.'
  exit 1
fi

if [ ! -f $BASEDIR/target/dependency/heapstats-core*.jar ]; then
  mvn dependency:copy-dependencies
fi

$JAVA_HOME/bin/jshell \
    --class-path $BASEDIR/target/dependency/heapstats-core*.jar \
    --feedback heapstats \
    $BASEDIR/heapstats.jsh
