#!/bin/sh

# Copyright (C) 2017-2019, Yasumasa Suenaga
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.


BASEDIR=`dirname $0`

if [ -z "$JAVA_HOME" ]; then
  echo '$JAVA_HOME is required.'
  exit 1
fi

MAJOR_VER=`$JAVA_HOME/bin/java -XshowSettings:properties --version 2>&1 | grep java.specification.version | sed -e 's/^\(.\+\)= \([0-9]\+\)$/\2/'`
if [ -z "$MAJOR_VER" ] || [ $MAJOR_VER -lt 11 ]; then
  echo 'JDK 11 or later is required.'
  exit 2
fi

if [ ! -f $BASEDIR/target/dependency/heapstats-core*.jar ]; then
  mvn dependency:copy-dependencies
fi

$JAVA_HOME/bin/jshell \
    --module-path $BASEDIR/target/dependency \
    --add-module heapstats.core \
    --feedback heapstats \
    $BASEDIR/heapstats.jsh
